"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mainwindow.py']
DATA_FILES = ['Wrote', 'setup.py', 'chrome.txt', 'ff.txt','ie.txt','opera.txt','logo.ico','logo.png','./logo.icns']
OPTIONS = {'argv_emulation': True,
           'includes': ['requests', 'bs4','PyQt5', 'packaging'],
           'iconfile': './logo.icns',
           'packages': ['requests', 'bs4','PyQt5', 'packaging']
           }


setup(
    app=APP,
    name='PC Browser Deployment Manager',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


# sudo pip install -U py2app
## py2applet --make-setup mainwindow.py Wrote setup.py
# rm -rf build dist
# python setup.py py2app -A --iconfile ./logo.icns
# python setup.py py2app -A



# pip install pyinstaller
# pyinstaller -w mainwindow.py --hidden-import PyQt5.sip --specpath
# pyinstaller --windowed --onefile --clean --noconfirm main.py
# pyinstaller mainwindow.spec
